dist: trusty
language: java
before_install: 
    - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
script:
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - echo java -version
  - mvn test
  
env: JDK='OpenJDK 10'
install: . ./install-jdk.sh -F 10 -L GPL